-- Migration: Add vendor normalization columns
-- Date: 2026-01-02
-- Description: Adds normalized_vendor and vendor_override columns to transactions table
--              for the vendor normalization system

-- Forward migration
BEGIN;

-- Add normalized_vendor column (auto-generated by import)
ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS normalized_vendor TEXT;

-- Add vendor_override column (user manual override)
ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS vendor_override TEXT;

-- Add indexes for query performance
CREATE INDEX IF NOT EXISTS idx_transactions_normalized_vendor
ON transactions(normalized_vendor);

CREATE INDEX IF NOT EXISTS idx_transactions_vendor_override
ON transactions(vendor_override);

-- Add missing indexes for performance (from PAIN_POINTS.md)
CREATE INDEX IF NOT EXISTS idx_transactions_member_id
ON transactions(member_id);

CREATE INDEX IF NOT EXISTS idx_transactions_vendor
ON transactions(vendor);

-- Add documentation comments
COMMENT ON COLUMN transactions.normalized_vendor IS
'Auto-generated normalized vendor name using pattern rules (e.g., "AMAZON MKTPL*XYZ" -> "Amazon")';

COMMENT ON COLUMN transactions.vendor_override IS
'User-defined override for vendor display name. Takes priority over normalized_vendor.';

COMMIT;

-- Rollback (for reference, execute manually if needed)
-- BEGIN;
-- DROP INDEX IF EXISTS idx_transactions_normalized_vendor;
-- DROP INDEX IF EXISTS idx_transactions_vendor_override;
-- ALTER TABLE transactions DROP COLUMN IF EXISTS normalized_vendor;
-- ALTER TABLE transactions DROP COLUMN IF EXISTS vendor_override;
-- COMMIT;
